### PR TITLE
Build executables

### PR DESCRIPTION
**Pull request by qixils**
Automatically compiles executable artifacts (i.e. `.exe`s, `.app`s, and `.AppImage`s) for every commit/pull request. Also, should a v1.6.3 ever be released to GitHub, it will also automatically upload the artifacts to releases as well

This one doesn't close any issues but cmon who doesn't want free and easy proper `.AppImage`s for Linux :D 

edit: just remembered these will read save files from a different directory than 1.6, marking as draft for now

### CODE REVIEW

**Comment by Stabyourself** [comment]
Hey, thanks a lot for the pull requests, everything looks good. I'll have to look at automatic building, got no experience on github on this. I don't think the save dir change is too much of an issue really.

**Comment by qixils** [comment]
Went and fixed the save dir issue anyway by just adding a check to ensure it's `LOVE/mari0` instead of just `mari0`. You can check out the build logs and artifacts [here](https://github.com/qixils/mari0/actions/runs/5365446330/jobs/9734269532). To build locally you install the `makelove` package from PyPi (`py -m pip install makelove`) and then just run `py -m makelove` in the game's root folder.

**Comment by Stabyourself** [comment]
Thanks a lot! When I have the time, I gotta take a look at this to fix the macos issues since apple made that change.

**Comment by qixils** [comment]
Oh yeah, I'm pretty sure this fixes #32 but I'll double check

**Pull request merged**
