### PR TITLE
LOVE 0.10.1 support

### PR DESCRIPTION
**Pull request by tzvetkoff**
A brief list of changes:

- Drawing methods in 0.9 got simplified - e.g. `draw` instead of `drawq`
- Other APIs got changed as well, e.g. `filesystem`
- Threads share variables through "channels", there's no `set` or `get`
  anymore
- Seems like GIF support was dropped (algnough there's no mention in
  LOVE's documentation), so the icon was converted to PNG
- Non-PO2 shader support is guaranteed now, checks removed
- Mouse clicks now emit numbers for buttons instead of strings
- Mouse wheel events got their own callback now, giving the change in
  x/y (we're only using the vertical wheel currently)
- Added a .gitignore

### CODE REVIEW

**Comment by Stabyourself** [comment]
I will take a look at it and approve (or whatever you call it in GIT lingo) as soon as I get to it!
Thanks a lot!

**Comment by tzvetkoff** [comment]
OK, hold on a second please :-)

**Comment by tzvetkoff** [comment]
I've just found out that I haven't updated the joystick handling code :-(
Working on it, will add one more commit soon.

**Comment by tzvetkoff** [comment]
Well, done. Just played a nice game with my Nimbus controller.

The main reason I undertook the LÖVE 0.10.1 update was SDL2 and the better controller support. Older LÖVE/SDL versions didn't support the D-Pad of my controller (and probably other controllers as well) at all :-)

**Comment by Stabyourself** [comment]
Hey man, I hope I did everything right merging your changes.

**Comment by tzvetkoff** [comment]
Yeah, everything is OK.
I guess I've missed a few more spots myself :-(
Anyway, when you believe it's ready you can bump a new version and make it available for download :-)

**Pull request merged**
